import { useState } from 'react'
import { useNavigate, useSearchParams } from 'react-router-dom'
import { useAuth } from '../contexts/AuthContext'
import Logo from '../components/Logo'

const TERMS = {
  title: 'Terms of Service',
  content: [
    { heading: '1. Acceptance of Terms', body: 'By creating an account or using HireLens, you agree to these Terms of Service. If you do not agree, please do not use the platform.' },
    { heading: '2. Use of Service', body: 'HireLens provides AI-powered interview coaching and resume analysis tools. You agree to use the platform only for lawful purposes and in a way that does not infringe the rights of others.' },
    { heading: '3. Account Responsibility', body: 'You are responsible for maintaining the confidentiality of your account credentials. All activity under your account is your responsibility. Notify us immediately of any unauthorized use.' },
    { heading: '4. AI-Generated Content', body: 'Feedback and analysis provided by HireLens is generated by AI and is for informational purposes only. It does not guarantee job placement or interview success.' },
    { heading: '5. Intellectual Property', body: 'All content, features, and functionality of HireLens — including logos, design, and software — are owned by HireLens and protected by applicable intellectual property laws.' },
    { heading: '6. Termination', body: 'We reserve the right to suspend or terminate your account at our discretion if you violate these terms or engage in behavior harmful to the platform or its users.' },
    { heading: '7. Limitation of Liability', body: 'HireLens is provided "as is" without warranties of any kind. We are not liable for any indirect, incidental, or consequential damages arising from your use of the platform.' },
    { heading: '8. Changes to Terms', body: 'We may update these terms at any time. Continued use of HireLens after changes constitutes acceptance of the revised terms.' },
    { heading: '9. Contact', body: 'For questions about these terms, contact us at support@hirelens.ai' },
  ]
}

const PRIVACY = {
  title: 'Privacy Policy',
  content: [
    { heading: '1. Information We Collect', body: 'We collect information you provide directly — such as your name, email address, and password — as well as data generated through your use of the platform, including interview responses and resume content.' },
    { heading: '2. How We Use Your Information', body: 'We use your data to provide, improve, and personalize the HireLens experience; to send you relevant notifications; and to analyze usage patterns to enhance our AI models.' },
    { heading: '3. Data Storage', body: 'Your data is stored securely using Supabase infrastructure with industry-standard encryption at rest and in transit. We do not sell your personal data to third parties.' },
    { heading: '4. AI Processing', body: 'Your interview answers and resume content are processed by AI models to generate feedback. This data is handled securely and is not shared with other users.' },
    { heading: '5. Cookies', body: 'HireLens uses cookies and similar technologies to maintain your session and improve your experience. You can control cookie settings through your browser.' },
    { heading: '6. Third-Party Services', body: 'We use trusted third-party services (including Google OAuth and Supabase) that have their own privacy policies. We encourage you to review them.' },
    { heading: '7. Your Rights', body: 'You may request access to, correction of, or deletion of your personal data at any time by contacting us at privacy@hirelens.ai' },
    { heading: '8. Children\'s Privacy', body: 'HireLens is not directed to children under 13. We do not knowingly collect personal information from children.' },
    { heading: '9. Changes to This Policy', body: 'We may update this Privacy Policy periodically. We will notify you of significant changes via email or a notice on the platform.' },
    { heading: '10. Contact', body: 'For privacy-related questions, contact us at privacy@hirelens.ai' },
  ]
}

function LegalModal({ doc, onClose }) {
  return (
    <div className="legal-overlay" onClick={onClose}>
      <div className="legal-modal" onClick={e => e.stopPropagation()}>
        <div className="legal-header">
          <h2 className="legal-title">{doc.title}</h2>
          <button className="legal-close" onClick={onClose}>
            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" width="18" height="18" strokeLinecap="round" strokeLinejoin="round">
              <line x1="18" y1="6" x2="6" y2="18"/><line x1="6" y1="6" x2="18" y2="18"/>
            </svg>
          </button>
        </div>
        <div className="legal-body">
          <p className="legal-date">Last updated: April 8, 2026</p>
          {doc.content.map(section => (
            <div key={section.heading} className="legal-section">
              <h3 className="legal-section-heading">{section.heading}</h3>
              <p className="legal-section-body">{section.body}</p>
            </div>
          ))}
        </div>
        <div className="legal-footer">
          <button className="legal-agree-btn" onClick={onClose}>I Understand</button>
        </div>
      </div>
    </div>
  )
}

export default function Login() {
  const { signIn, signUp, signInWithGoogle, signInWithLinkedIn, resetPassword } = useAuth()
  const navigate = useNavigate()

  const [searchParams] = useSearchParams()
  const [tab,      setTab]      = useState(() => searchParams.get('tab') === 'signup' ? 'signup' : 'signin')
  const [forgotView,  setForgotView]  = useState(false)
  const [forgotEmail, setForgotEmail] = useState('')
  const [forgotSent,  setForgotSent]  = useState(false)
  const [forgotLoading, setForgotLoading] = useState(false)
  const [email,    setEmail]    = useState('')
  const [password, setPassword] = useState('')
  const [showPwd,  setShowPwd]  = useState(false)
  const [loading,  setLoading]  = useState(false)
  const [error,    setError]    = useState('')

  const [name,     setName]     = useState('')
  const [confirm,  setConfirm]  = useState('')
  const [showPwd2, setShowPwd2] = useState(false)
  const [agreed,   setAgreed]   = useState(false)
  const [modal,    setModal]    = useState(null) // 'terms' | 'privacy' | null

  function switchTab(t) { setTab(t); setError('') }

  async function handleSignIn(e) {
    e.preventDefault(); setError('')
    if (!email || !password) return setError('Please fill in all fields.')
    setLoading(true)
    try { await signIn(email, password); navigate('/dashboard') }
    catch (err) {
      setError((err.message || '').toLowerCase().includes('invalid')
        ? 'Incorrect email or password.' : 'Something went wrong.')
    } finally { setLoading(false) }
  }

  async function handleSignUp(e) {
    e.preventDefault(); setError('')
    if (!name || !email || !password) return setError('Please fill in all fields.')
    if (password.length < 6) return setError('Password must be at least 6 characters.')
    if (password !== confirm) return setError('Passwords do not match.')
    if (!agreed) return setError('Please agree to the Terms & Privacy Policy.')
    setLoading(true)
    try { await signUp(name, email, password); navigate('/dashboard') }
    catch (err) {
      const msg = err.message || ''
      setError(msg.includes('already registered') ? 'That email is already in use.' : msg || 'Sign up failed.')
    } finally { setLoading(false) }
  }

  async function handleForgot(e) {
    e.preventDefault()
    if (!forgotEmail) return setError('Please enter your email.')
    setForgotLoading(true); setError('')
    try {
      await resetPassword(forgotEmail)
      setForgotSent(true)
    } catch { setError('Could not send reset email. Please try again.') }
    finally { setForgotLoading(false) }
  }

  const EyeOpen  = () => <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" width="17" height="17" strokeLinecap="round" strokeLinejoin="round"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"/><circle cx="12" cy="12" r="3"/></svg>
  const EyeClose = () => <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" width="17" height="17" strokeLinecap="round" strokeLinejoin="round"><path d="M17.94 17.94A10.07 10.07 0 0 1 12 20c-7 0-11-8-11-8a18.45 18.45 0 0 1 5.06-5.94"/><path d="M9.9 4.24A9.12 9.12 0 0 1 12 4c7 0 11 8 11 8a18.5 18.5 0 0 1-2.16 3.19"/><line x1="1" y1="1" x2="23" y2="23"/></svg>

  return (
    <div className="ac-bg">

      {/* decorative blobs on the outer bg */}
      <div className="ac-blob-tl" />
      <div className="ac-blob-br" />

      {/* ── The single centered card ── */}
      <div className="ac-card">

        {/* LEFT — form side */}
        <div className="ac-form-side">
          <div className="ac-logo" style={{ cursor:'pointer' }} onClick={() => navigate('/')}>
            <Logo size={26} />
            <span>HireLens</span>
          </div>

          {/* ── Forgot Password View ── */}
          {forgotView ? (
            <>
              <button className="ac-back-btn" onClick={() => { setForgotView(false); setForgotSent(false); setError('') }}>
                <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" width="16" height="16" strokeLinecap="round" strokeLinejoin="round"><polyline points="15 18 9 12 15 6"/></svg>
                Back to Login
              </button>

              {forgotSent ? (
                <div className="ac-forgot-success">
                  <div className="ac-forgot-icon">
                    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" width="32" height="32" strokeLinecap="round" strokeLinejoin="round"><path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07A19.5 19.5 0 0 1 4.69 12 19.79 19.79 0 0 1 1.64 3.28 2 2 0 0 1 3.61 1h3a2 2 0 0 1 2 1.72c.127.96.361 1.903.7 2.81a2 2 0 0 1-.45 2.11L7.91 8.6a16 16 0 0 0 6 6l.96-.96a2 2 0 0 1 2.11-.45c.907.339 1.85.573 2.81.7A2 2 0 0 1 21.73 16z"/></svg>
                  </div>
                  <h2 className="ac-title" style={{ fontSize:'1.4rem' }}>Check your email!</h2>
                  <p className="ac-sub">We sent a password reset link to<br/><strong>{forgotEmail}</strong></p>
                  <p className="ac-sub" style={{ fontSize:12, marginTop:8 }}>Didn't receive it? Check your spam folder or{' '}
                    <button type="button" className="ac-link" onClick={() => setForgotSent(false)}>try again</button>
                  </p>
                </div>
              ) : (
                <>
                  <h1 className="ac-title">Forgot Password?</h1>
                  <p className="ac-sub">Enter your email and we'll send you a reset link.</p>
                  {error && <div className="ac-error">{error}</div>}
                  <form onSubmit={handleForgot} noValidate>
                    <div className="ac-field">
                      <span className="ac-icon">
                        <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" width="17" height="17" strokeLinecap="round" strokeLinejoin="round"><path d="M4 4h16c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2z"/><polyline points="22,6 12,13 2,6"/></svg>
                      </span>
                      <input className="ac-input" type="email" placeholder="Enter your email"
                        value={forgotEmail} onChange={e => setForgotEmail(e.target.value)} autoComplete="email" required />
                    </div>
                    <button type="submit" className="ac-submit" disabled={forgotLoading}>
                      {forgotLoading
                        ? <span className="spinner" style={{ width:18,height:18,borderWidth:2,display:'inline-block',verticalAlign:'middle' }}/>
                        : 'Send Reset Link'}
                    </button>
                  </form>
                </>
              )}
            </>
          ) : (
          <>

          <h1 className="ac-title">{tab === 'signin' ? 'LOGIN' : 'SIGN UP'}</h1>
          <p className="ac-sub">
            {tab === 'signin'
              ? 'Welcome back! Sign in to continue.'
              : 'Create your account and start your journey.'}
          </p>

          {/* Tabs */}
          <div className="ac-tabs">
            <button className={`ac-tab ${tab === 'signin' ? 'ac-tab-on' : ''}`} onClick={() => switchTab('signin')}>Sign In</button>
            <button className={`ac-tab ${tab === 'signup' ? 'ac-tab-on' : ''}`} onClick={() => switchTab('signup')}>Sign Up</button>
          </div>

          {error && <div className="ac-error">{error}</div>}

          {/* ── Sign In ── */}
          {tab === 'signin' && (
            <form onSubmit={handleSignIn} noValidate>

              <div className="ac-field">
                <span className="ac-icon">
                  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" width="17" height="17" strokeLinecap="round" strokeLinejoin="round"><path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"/><circle cx="12" cy="7" r="4"/></svg>
                </span>
                <input className="ac-input" type="email" placeholder="Username or Email"
                  value={email} onChange={e => setEmail(e.target.value)} autoComplete="email" required />
              </div>

              <div className="ac-field">
                <span className="ac-icon">
                  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" width="17" height="17" strokeLinecap="round" strokeLinejoin="round"><rect x="3" y="11" width="18" height="11" rx="2"/><path d="M7 11V7a5 5 0 0 1 10 0v4"/></svg>
                </span>
                <input className="ac-input" type={showPwd ? 'text' : 'password'} placeholder="Password"
                  value={password} onChange={e => setPassword(e.target.value)} autoComplete="current-password" required />
                <button type="button" className="ac-eye" onClick={() => setShowPwd(v => !v)}>
                  {showPwd ? <EyeClose/> : <EyeOpen/>}
                </button>
              </div>

              <div className="ac-row-between">
                <label className="ac-check-label">
                  <input type="checkbox" className="ac-checkbox" /> Remember me
                </label>
                <button type="button" className="ac-forgot" onClick={() => { setForgotView(true); setError('') }}>Forgot Password?</button>
              </div>

              <button type="submit" className="ac-submit" disabled={loading}>
                {loading ? <span className="spinner" style={{ width:18,height:18,borderWidth:2,display:'inline-block',verticalAlign:'middle' }}/> : 'Login Now'}
              </button>

              <div className="ac-divider"><span><b>Login</b> with Others</span></div>

              <button type="button" className="ac-social" onClick={signInWithGoogle}>
                <svg viewBox="0 0 24 24" width="18" height="18"><path fill="#4285F4" d="M22.56 12.25c0-.78-.07-1.53-.2-2.25H12v4.26h5.92c-.26 1.37-1.04 2.53-2.21 3.31v2.77h3.57c2.08-1.92 3.28-4.74 3.28-8.09z"/><path fill="#34A853" d="M12 23c2.97 0 5.46-.98 7.28-2.66l-3.57-2.77c-.98.66-2.23 1.06-3.71 1.06-2.86 0-5.29-1.93-6.16-4.53H2.18v2.84C3.99 20.53 7.7 23 12 23z"/><path fill="#FBBC05" d="M5.84 14.09c-.22-.66-.35-1.36-.35-2.09s.13-1.43.35-2.09V7.07H2.18C1.43 8.55 1 10.22 1 12s.43 3.45 1.18 4.93l2.85-2.22.81-.62z"/><path fill="#EA4335" d="M12 5.38c1.62 0 3.06.56 4.21 1.64l3.15-3.15C17.45 2.09 14.97 1 12 1 7.7 1 3.99 3.47 2.18 7.07l3.66 2.84c.87-2.6 3.3-4.53 6.16-4.53z"/></svg>
                Login with <b>Google</b>
              </button>

              <button type="button" className="ac-social" onClick={signInWithLinkedIn}>
                <svg viewBox="0 0 24 24" width="18" height="18" fill="#0A66C2"><path d="M20.447 20.452h-3.554v-5.569c0-1.328-.027-3.037-1.852-3.037-1.853 0-2.136 1.445-2.136 2.939v5.667H9.351V9h3.414v1.561h.046c.477-.9 1.637-1.85 3.37-1.85 3.601 0 4.267 2.37 4.267 5.455v6.286zM5.337 7.433a2.062 2.062 0 0 1-2.063-2.065 2.064 2.064 0 1 1 2.063 2.065zm1.782 13.019H3.555V9h3.564v11.452zM22.225 0H1.771C.792 0 0 .774 0 1.729v20.542C0 23.227.792 24 1.771 24h20.451C23.2 24 24 23.227 24 22.271V1.729C24 .774 23.2 0 22.222 0h.003z"/></svg>
                Login with <b>LinkedIn</b>
              </button>

              <p className="ac-switch">
                Don't have an account?{' '}
                <button type="button" className="ac-switch-btn" onClick={() => switchTab('signup')}>Sign Up</button>
              </p>
            </form>
          )}

          {/* ── Sign Up ── */}
          {tab === 'signup' && (
            <form onSubmit={handleSignUp} noValidate>

              <div className="ac-field">
                <span className="ac-icon">
                  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" width="17" height="17" strokeLinecap="round" strokeLinejoin="round"><path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"/><circle cx="12" cy="7" r="4"/></svg>
                </span>
                <input className="ac-input" type="text" placeholder="Full Name"
                  value={name} onChange={e => setName(e.target.value)} autoComplete="name" required />
              </div>

              <div className="ac-field">
                <span className="ac-icon">
                  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" width="17" height="17" strokeLinecap="round" strokeLinejoin="round"><path d="M4 4h16c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2z"/><polyline points="22,6 12,13 2,6"/></svg>
                </span>
                <input className="ac-input" type="email" placeholder="Email Address"
                  value={email} onChange={e => setEmail(e.target.value)} autoComplete="email" required />
              </div>

              <div className="ac-field">
                <span className="ac-icon">
                  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" width="17" height="17" strokeLinecap="round" strokeLinejoin="round"><rect x="3" y="11" width="18" height="11" rx="2"/><path d="M7 11V7a5 5 0 0 1 10 0v4"/></svg>
                </span>
                <input className="ac-input" type={showPwd ? 'text' : 'password'} placeholder="Password"
                  value={password} onChange={e => setPassword(e.target.value)} autoComplete="new-password" required />
                <button type="button" className="ac-eye" onClick={() => setShowPwd(v => !v)}>
                  {showPwd ? <EyeClose/> : <EyeOpen/>}
                </button>
              </div>

              <div className="ac-field">
                <span className="ac-icon">
                  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" width="17" height="17" strokeLinecap="round" strokeLinejoin="round"><rect x="3" y="11" width="18" height="11" rx="2"/><path d="M7 11V7a5 5 0 0 1 10 0v4"/></svg>
                </span>
                <input className="ac-input" type={showPwd2 ? 'text' : 'password'} placeholder="Confirm Password"
                  value={confirm} onChange={e => setConfirm(e.target.value)} autoComplete="new-password" required />
                <button type="button" className="ac-eye" onClick={() => setShowPwd2(v => !v)}>
                  {showPwd2 ? <EyeClose/> : <EyeOpen/>}
                </button>
              </div>

              <label className="ac-check-label" style={{ marginBottom:14 }}>
                <input type="checkbox" className="ac-checkbox" checked={agreed} onChange={e => setAgreed(e.target.checked)} />
                I agree to the <button type="button" className="ac-link" onClick={() => setModal('terms')}>Terms</button> &amp; <button type="button" className="ac-link" onClick={() => setModal('privacy')}>Privacy Policy</button>
              </label>

              <button type="submit" className="ac-submit" disabled={loading}>
                {loading ? <span className="spinner" style={{ width:18,height:18,borderWidth:2,display:'inline-block',verticalAlign:'middle' }}/> : 'Create Account'}
              </button>

              <div className="ac-divider"><span><b>Sign up</b> with Others</span></div>

              <button type="button" className="ac-social" onClick={signInWithGoogle}>
                <svg viewBox="0 0 24 24" width="18" height="18"><path fill="#4285F4" d="M22.56 12.25c0-.78-.07-1.53-.2-2.25H12v4.26h5.92c-.26 1.37-1.04 2.53-2.21 3.31v2.77h3.57c2.08-1.92 3.28-4.74 3.28-8.09z"/><path fill="#34A853" d="M12 23c2.97 0 5.46-.98 7.28-2.66l-3.57-2.77c-.98.66-2.23 1.06-3.71 1.06-2.86 0-5.29-1.93-6.16-4.53H2.18v2.84C3.99 20.53 7.7 23 12 23z"/><path fill="#FBBC05" d="M5.84 14.09c-.22-.66-.35-1.36-.35-2.09s.13-1.43.35-2.09V7.07H2.18C1.43 8.55 1 10.22 1 12s.43 3.45 1.18 4.93l2.85-2.22.81-.62z"/><path fill="#EA4335" d="M12 5.38c1.62 0 3.06.56 4.21 1.64l3.15-3.15C17.45 2.09 14.97 1 12 1 7.7 1 3.99 3.47 2.18 7.07l3.66 2.84c.87-2.6 3.3-4.53 6.16-4.53z"/></svg>
                Sign up with <b>Google</b>
              </button>

              <p className="ac-switch">
                Already have an account?{' '}
                <button type="button" className="ac-switch-btn" onClick={() => switchTab('signin')}>Sign In</button>
              </p>
            </form>
          )}

          </>
          )} {/* end forgotView ternary */}
        </div>

        {/* RIGHT — illustration side */}
        <div className="ac-art-side">
          {/* wave rings */}
          <div className="ac-ring ac-ring-1" />
          <div className="ac-ring ac-ring-2" />
          <div className="ac-ring ac-ring-3" />

          {/* inner portrait card */}
          <div className="ac-portrait">
            {/* person: CSS figure holding tablet */}
            <div className="ac-fig">
              {/* hair */}
              <div className="ac-fig-hair" />
              {/* face */}
              <div className="ac-fig-face">
                <div className="ac-fig-eye ac-fig-eye-l" />
                <div className="ac-fig-eye ac-fig-eye-r" />
                <div className="ac-fig-smile" />
              </div>
              {/* neck */}
              <div className="ac-fig-neck" />
              {/* shirt / body */}
              <div className="ac-fig-body" />
              {/* arms holding tablet */}
              <div className="ac-fig-arm ac-fig-arm-l" />
              <div className="ac-fig-arm ac-fig-arm-r" />
              {/* tablet */}
              <div className="ac-fig-tablet">
                <div className="ac-fig-screen" />
              </div>
              {/* skirt */}
              <div className="ac-fig-skirt" />
            </div>
          </div>

          {/* lightning badge */}
          <div className="ac-bolt">
            <svg viewBox="0 0 24 24" fill="#F59E0B" width="24" height="24">
              <polygon points="13 2 3 14 12 14 11 22 21 10 12 10 13 2"/>
            </svg>
          </div>

          {/* headline text */}
          <div className="ac-art-text">
            <p>Very good works are<br/>waiting for you<br/><span>Login Now!!!</span></p>
          </div>
        </div>

      </div>{/* /ac-card */}

      {modal && (
        <LegalModal
          doc={modal === 'terms' ? TERMS : PRIVACY}
          onClose={() => setModal(null)}
        />
      )}
    </div>
  )
}
